// 代码生成时间: 2025-08-08 12:00:01
package com.yourcompany.excelautogenerator;

import io.quarkus.runtime.QuarkusApplication;
import io.quarkus.runtime.annotations.QuarkusMain;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.function.Consumer;

/**
 * The main class, which implements the QuarkusApplication interface.
 */
@QuarkusMain
public class ExcelAutoGenerator implements QuarkusApplication {

    private Workbook workbook;
    private Sheet sheet;

    /**
     * Create a new Excel workbook and sheet.
     */
    public ExcelAutoGenerator() {
        this.workbook = new XSSFWorkbook();
        this.sheet = workbook.createSheet("AutoGeneratedExcel");
    }

    /**
     * Add a header row to the Excel sheet.
     *
     * @param headers A list of headers to be added.
     */
    public void addHeaderRow(String... headers) {
        Row headerRow = sheet.createRow(0);
        for (int i = 0; i < headers.length; i++) {
            headerRow.createCell(i).setCellValue(headers[i]);
        }
    }

    /**
     * Add a data row to the Excel sheet.
     *
     * @param data A list of data to be added.
     */
    public void addDataRow(String... data) {
        Row dataRow = sheet.createRow(sheet.getLastRowNum() + 1);
        for (int i = 0; i < data.length; i++) {
            dataRow.createCell(i).setCellValue(data[i]);
        }
    }

    /**
     * Saves the Excel workbook to the specified path.
     *
     * @param filePath The path where the Excel file will be saved.
     */
    public void saveExcelFile(String filePath) {
        try (FileOutputStream outputStream = new FileOutputStream(filePath)) {
            workbook.write(outputStream);
            workbook.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public int run(String... args) {
        try {
            // Add a header row
            addHeaderRow("ID", "Name", "Age");

            // Add data rows
            addDataRow("1", "John Doe", "30");
            addDataRow("2", "Jane Smith", "25");

            // Save the Excel file
            saveExcelFile("auto_generated_excel.xlsx");

        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Main method for standalone execution.
     * @param args Command line arguments.
     */
    public static void main(String... args) {
        new ExcelAutoGenerator().run(args);
    }
}
